### ISSUE TITLE
Position of the zapzap window is everytime on an new position

### ISSUE THREAD

**Issue by staubflocke** [zapzap-linux/zapzap#10]
When zapzap is closed or minimized in tray and I click to open, the window opens in a new place every time.

I move the window to the rightmost and bottom position on the desktop in the corner.

![Bildschirmfoto zu 2023-11-16 20-58-47](https://github.com/zapzap-linux/zapzap/assets/151079336/06417f06-651f-4314-9bbd-bb15e634d9fc)

I close the window and it disappears into the tray.
I click on the tray-icon and a new window opens on a new position.

![Bildschirmfoto zu 2023-11-16 20-59-00](https://github.com/zapzap-linux/zapzap/assets/151079336/baf3f9a9-970f-46b3-81dd-6cc2103df2c5)

I close the window again and it disappears into the tray.
I click on the tray-icon and a new window opens again on a new position.

![Bildschirmfoto zu 2023-11-16 20-59-13](https://github.com/zapzap-linux/zapzap/assets/151079336/84bc474b-8af7-4903-ae73-bb3aec8eeba6)

That's annoying.

I'm using Linux Mint - Version Linux Mint 21.2 Victoria 64-bit, Kernel Linux 5.15.0-87-generic x86_64, MATE 1.26.0.

Regards, Michael

**Comment by rafatosta** [comment]
> When zapzap is closed or minimized in tray and I click to open, the window opens in a new place every time.
> 
> I move the window to the rightmost and bottom position on the desktop in the corner.
> 
> ![Bildschirmfoto zu 2023-11-16 20-58-47](https://github.com/zapzap-linux/zapzap/assets/151079336/06417f06-651f-4314-9bbd-bb15e634d9fc)
> 
> I close the window and it disappears into the tray.
> I click on the tray-icon and a new window opens on a new position.
> 
> ![Bildschirmfoto zu 2023-11-16 20-59-00](https://github.com/zapzap-linux/zapzap/assets/151079336/baf3f9a9-970f-46b3-81dd-6cc2103df2c5)
> 
> I close the window again and it disappears into the tray.
> I click on the tray-icon and a new window opens again on a new position.
> 
> ![Bildschirmfoto zu 2023-11-16 20-59-13](https://github.com/zapzap-linux/zapzap/assets/151079336/84bc474b-8af7-4903-ae73-bb3aec8eeba6)
> 
> That's annoying.
> 
> I'm using Linux Mint - Version Linux Mint 21.2 Victoria 64-bit, Kernel Linux 5.15.0-87-generic x86_64, MATE 1.26.0.
> 
> Regards, Michael

This is Wayland's "fault". If you use x11 it works perfectly. 

I had already seen this problem and decided to investigate why it wasn't working.

**Comment by rafatosta** [comment]
> When zapzap is closed or minimized in tray and I click to open, the window opens in a new place every time.
> 
> I move the window to the rightmost and bottom position on the desktop in the corner.
> 
> ![Bildschirmfoto zu 2023-11-16 20-58-47](https://github.com/zapzap-linux/zapzap/assets/151079336/06417f06-651f-4314-9bbd-bb15e634d9fc)
> 
> I close the window and it disappears into the tray.
> I click on the tray-icon and a new window opens on a new position.
> 
> ![Bildschirmfoto zu 2023-11-16 20-59-00](https://github.com/zapzap-linux/zapzap/assets/151079336/baf3f9a9-970f-46b3-81dd-6cc2103df2c5)
> 
> I close the window again and it disappears into the tray.
> I click on the tray-icon and a new window opens again on a new position.
> 
> ![Bildschirmfoto zu 2023-11-16 20-59-13](https://github.com/zapzap-linux/zapzap/assets/151079336/84bc474b-8af7-4903-ae73-bb3aec8eeba6)
> 
> That's annoying.
> 
> I'm using Linux Mint - Version Linux Mint 21.2 Victoria 64-bit, Kernel Linux 5.15.0-87-generic x86_64, MATE 1.26.0.
> 
> Regards, Michael

This is Wayland's "fault". If you use x11 it works perfectly. 

I had already seen this problem and decided to investigate why it wasn't working.

**Comment by staubflocke** [comment]
> This is Wayland's "fault". If you use x11 it works perfectly.
> 
> I had already seen this problem and decided to investigate why it wasn't working.
My display server is x11. That cannot be the reason.

```
michael@mint:~$ echo $XDG_SESSION_TYPE
x11
michael@mint:~$ 
```

I cannot remember that another application makes such problems.

Linux Mint Cinnamon next version 21.3 should experimental support wayland.

cu, Michael

**Comment by rafatosta** [comment]
> > This is Wayland's "fault". If you use x11 it works perfectly.
> > I had already seen this problem and decided to investigate why it wasn't working.
> 
> My display server is x11. That cannot be the reason.
> 
> ```
> michael@mint:~$ echo $XDG_SESSION_TYPE
> x11
> michael@mint:~$ 
> ```
> 
> I cannot remember that another application makes such problems.
> 
> Linux Mint Cinnamon next version 21.3 should experimental support wayland.
> 
> cu, Michael

Check it on flatseal and uncheck Wayland's option.This behavior only happens when Zapzap is being executed in Wayland.

**Comment by staubflocke** [comment]
> Check it on flatseal and uncheck Wayland's option.This behavior only happens when Zapzap is being executed in Wayland.

I've forgotten, that zapzap is a flatpak.

But there is no change after that. Look at the video from SimpleScreenRecorder.

https://github.com/zapzap-linux/zapzap/assets/151079336/0fc8b43f-45fc-47a2-846e-dc36ad35a20f

cu, Michael

**Comment by rafatosta** [comment]
> > Check it on flatseal and uncheck Wayland's option.This behavior only happens when Zapzap is being executed in Wayland.
> 
> I've forgotten, that zapzap is a flatpak.
> 
> But there is no change after that. Look at the video from SimpleScreenRecorder.
> 
>  zapzap-with-flatseal.mp4 
> cu, Michael

It cost. I'll install Mint on a VM and try to reproduce. Once identified, I make the correction.
