### ISSUE TITLE
[Feature] Ability to change font size and family for zapzap interface and WhatsApp Web inside zapzap

### ISSUE THREAD

**Issue by iAweX** [zapzap-linux/zapzap#13]
Please add an ability to change font size and family for zapzap interface and WhatsApp Web inside zapzap.

**Comment by rafatosta** [comment]
Ctrl + not work?

> Please add an ability to change font size and family for zapzap interface and WhatsApp Web inside zapzap.

Ctrl + not work?

**Comment by iAweX** [comment]
> > Please add an ability to change font size and family for zapzap interface and WhatsApp Web inside zapzap.
> 
> Ctrl + not work?

Ctrl + changes only font size of webapp, but not zapzap interface (menu, settings, etc.). Also Ctrl+- change only size, but not family. For example I like Roboto, but I can't use it in zapzap.

**Comment by rafatosta** [comment]
I'll try to synchronize the font size of the rest of the application, it really is a problem.

I don't know if WhatsappWeb accepts font changes. If you accept, I can make an alternative to change the font.
