### ISSUE TITLE
Menu borders too bold

### ISSUE THREAD

**Issue by iAweX** [zapzap-linux/zapzap#14]
IMHO on Debain 12 in x11 session menu borders looks too bold.

![image](https://github.com/zapzap-linux/zapzap/assets/50710418/d11083bb-2fe0-40e1-8c2c-b428b61c7059)

**Comment by rafatosta** [comment]
It's not a problem. This is the Qt standard for menus.

**Comment by iAweX** [comment]
Ok. This was only my opinion. What is interesting, some versions ago menu borders look thinner.
