### ISSUE TITLE
Tray icon with unread messages bug

### ISSUE THREAD

**Issue by mcdemon05** [zapzap-linux/zapzap#15]
Sometimes tray icon shows that have unread message
![image](https://github.com/zapzap-linux/zapzap/assets/15751984/a826f822-cc82-4e70-baae-73484a66c698)
but there aren't unread messages

How I can debug this?

FEDORA 39 GNOME

I use ZapZap with 2 users.

I tell you for sure.
There are no unread messages on both users.
But the icon can show supposedly there is one.

Then if someone writes to the user, the tray icon will still show 1 message. And if I read it, the icon will already be updated and will show that there are no messages.
But until no one has written, the icon may hang for a long time, that supposedly there is a message that does not exist.

Maybe you can add debug mode in zapzap? I would catch problem and collect logs.

**Comment by mcdemon05** [comment]
Problem still actual in 5 version

**Comment by o0nd7ots** [comment]
I am working with one user and I do not get this bug.
Still, it would be nice to know how to collect logs.

Maybe you can start the app from the command line?
