### ISSUE TITLE
[Bug] Downloading a large file fails

### ISSUE THREAD

**Issue by maniadevice** [zapzap-linux/zapzap#16]
Trying to download a large file (not an image or a video) causes the chat screen to go blank.

Steps to reproduce:
- Ask someone to send you a large file, preferably around 1.5GB+ (2GB is max?)
- Cick the icon to download, the download will begin showing the progress
- Wait for download to complete (I had my ZapZap window) minimised
- After download completes, the window turns blank without a popup to save the file

Version: Flatpak ZapZap version 4.5.5
OS: Linux Mint 21.2

I have attempted to do the same on other Whatsapp Flatpak wrappers, and it works fine.

**Comment by rafatosta** [comment]
I understand that this volume of data is part of its use, but I will not dedicate myself to this solution for now.
 I suggest using large file storage applications if you want to continue using Zapzap.
