### ISSUE TITLE
Fonts on Gnome Wayland with Fractional Scaling

### ISSUE THREAD

**Issue by llsaboya** [zapzap-linux/zapzap#17]
Hello Rafael. I bought a 4k monitor and noticed a strange behavior of the application. When I start on Wayland, the fonts look very strange when I activate fractional scaling in Gnome.

If I start on X11, they become blurry as usual.

I am using the Fedora Corp version. 

Here are some screenshots.

![Captura de tela de 2023-11-28 20-46-15](https://github.com/zapzap-linux/zapzap/assets/75430836/e18d23aa-20c3-46c8-bed4-d6f15813b58d)

![Captura de tela de 2023-11-28 20-43-51](https://github.com/zapzap-linux/zapzap/assets/75430836/f116574c-08d0-4560-96e1-0a09b5da4316)

![Captura de tela de 2023-11-28 20-41-19](https://github.com/zapzap-linux/zapzap/assets/75430836/a4469fa1-ba7d-421e-8caf-8880faa70602)

In despair, I tried:

![Captura de tela de 2023-11-28 20-45-32](https://github.com/zapzap-linux/zapzap/assets/75430836/b5cf1dc9-f786-4e76-9a06-10515189abd9)

:smiley:

**Comment by rafatosta** [comment]
Hi, I will look into this.
Does zooming through the app, Ctrl+, not solve your problem?

**Comment by llsaboya** [comment]
Zoom don't solve the problem.


![Captura de tela de 2023-11-29 08-38-24](https://github.com/zapzap-linux/zapzap/assets/75430836/95e0da8d-5ae3-48a2-ad3b-c61d94fc829e)

![Captura de tela de 2023-11-29 08-39-00](https://github.com/zapzap-linux/zapzap/assets/75430836/0f465409-3e9a-40d9-971c-ef3cbfe99c7e)

I build Zap local, but all I got was blurred fonts.

![Captura de tela de 2023-11-29 08-47-16](https://github.com/zapzap-linux/zapzap/assets/75430836/c3745cd5-61b7-4a5e-ab02-13926b6c5675)

Strange, because before I turned on Fractional Scaling it was working like a charm, even my build (I changed Segoe with the new Aptos font).

**Comment by rafatosta** [comment]
> Zoom don't solve the problem.
> 
> 
> ![Captura de tela de 2023-11-29 08-38-24](https://github.com/zapzap-linux/zapzap/assets/75430836/95e0da8d-5ae3-48a2-ad3b-c61d94fc829e)
> 
> ![Captura de tela de 2023-11-29 08-39-00](https://github.com/zapzap-linux/zapzap/assets/75430836/0f465409-3e9a-40d9-971c-ef3cbfe99c7e)
> 
> I build Zap local, but all I got was blurred fonts.
> 
> ![Captura de tela de 2023-11-29 08-47-16](https://github.com/zapzap-linux/zapzap/assets/75430836/c3745cd5-61b7-4a5e-ab02-13926b6c5675)
> 
> Strange, because before I turned on Fractional Scaling it was working like a charm, even my build (I changed Segoe with the new Aptos font).
> 
> 
> 

Great, the source is the problem. I was already wanting to change it anyway.

As you can see, I am preparing version 5.0. There will be no changes to features, just a redesign of the app's appearance and a greater focus on multiple users.

**Comment by rafatosta** [comment]
Could you send this font of these lyrics? Make a PR with the files, please

**Comment by rafatosta** [comment]
Could you send this font of these lyrics? Make a PR with the files, please

**Comment by llsaboya** [comment]
> > Zoom don't solve the problem.
> > ![Captura de tela de 2023-11-29 08-38-24](https://private-user-images.githubusercontent.com/75430836/286582109-95e0da8d-5ae3-48a2-ad3b-c61d94fc829e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzIzMDUsIm5iZiI6MTcwMTI3MjAwNSwicGF0aCI6Ii83NTQzMDgzNi8yODY1ODIxMDktOTVlMGRhOGQtNWFlMy00OGEyLWFkM2ItYzYxZDk0ZmM4MjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMjNmYTdmMTk5YWNiYWVmNjZiMjc4ZTcyYzIzM2E1ZDUyOTdkZjNiNzUwNmY3NzEzMWVlZTVlZDI2YjI4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nf4kUII0Y7buBgF4BuV18F28B5-abhznP8ywhKgEYFQ)
> > ![Captura de tela de 2023-11-29 08-39-00](https://private-user-images.githubusercontent.com/75430836/286582253-0f465409-3e9a-40d9-971c-ef3cbfe99c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzIzMDUsIm5iZiI6MTcwMTI3MjAwNSwicGF0aCI6Ii83NTQzMDgzNi8yODY1ODIyNTMtMGY0NjU0MDktM2U5YS00MGQ5LTk3MWMtZWYzY2JmZTk5YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZGM2YWJiZjEwNjQwOTJiOGM4NTM5MDM5NGE0ZTgzYjQ4NmMyM2NkMjE5ZjY3ZDhhY2M5NmRkYzk4MTZmY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FS81wjkLTERBTujiuWP6An57a47PX6_WIshKNzt_5dI)
> > I build Zap local, but all I got was blurred fonts.
> > ![Captura de tela de 2023-11-29 08-47-16](https://private-user-images.githubusercontent.com/75430836/286583170-c3745cd5-61b7-4a5e-ab02-13926b6c5675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzIzMDUsIm5iZiI6MTcwMTI3MjAwNSwicGF0aCI6Ii83NTQzMDgzNi8yODY1ODMxNzAtYzM3NDVjZDUtNjFiNy00YTVlLWFiMDItMTM5MjZiNmM1Njc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYTlhZDYzNTFjNmNjMmE0ZDM4OTllODg5ODRhYjJmY2VjNzI2MjI4NmY3MTA0ZTMyODIyNDZkOTc1NDg1NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X68vaPnaaX_T6QS9tCIGb4amaKwW8B_qK2lVIDyAVXg)
> > Strange, because before I turned on Fractional Scaling it was working like a charm, even my build (I changed Segoe with the new Aptos font).
> 
> Great, the source is the problem. I was already wanting to change it anyway.
> 
> As you can see, I am preparing version 5.0. There will be no changes to features, just a redesign of the app's appearance and a greater focus on multiple users.

Great. If you need testers, I am here. :smile:

**Comment by rafatosta** [comment]
> > > Zoom don't solve the problem.
> > > ![Captura de tela de 2023-11-29 08-38-24](https://private-user-images.githubusercontent.com/75430836/286582109-95e0da8d-5ae3-48a2-ad3b-c61d94fc829e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzIzMDUsIm5iZiI6MTcwMTI3MjAwNSwicGF0aCI6Ii83NTQzMDgzNi8yODY1ODIxMDktOTVlMGRhOGQtNWFlMy00OGEyLWFkM2ItYzYxZDk0ZmM4MjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMjNmYTdmMTk5YWNiYWVmNjZiMjc4ZTcyYzIzM2E1ZDUyOTdkZjNiNzUwNmY3NzEzMWVlZTVlZDI2YjI4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nf4kUII0Y7buBgF4BuV18F28B5-abhznP8ywhKgEYFQ)
> > > ![Captura de tela de 2023-11-29 08-39-00](https://private-user-images.githubusercontent.com/75430836/286582253-0f465409-3e9a-40d9-971c-ef3cbfe99c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzIzMDUsIm5iZiI6MTcwMTI3MjAwNSwicGF0aCI6Ii83NTQzMDgzNi8yODY1ODIyNTMtMGY0NjU0MDktM2U5YS00MGQ5LTk3MWMtZWYzY2JmZTk5YzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZGM2YWJiZjEwNjQwOTJiOGM4NTM5MDM5NGE0ZTgzYjQ4NmMyM2NkMjE5ZjY3ZDhhY2M5NmRkYzk4MTZmY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FS81wjkLTERBTujiuWP6An57a47PX6_WIshKNzt_5dI)
> > > I build Zap local, but all I got was blurred fonts.
> > > ![Captura de tela de 2023-11-29 08-47-16](https://private-user-images.githubusercontent.com/75430836/286583170-c3745cd5-61b7-4a5e-ab02-13926b6c5675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzIzMDUsIm5iZiI6MTcwMTI3MjAwNSwicGF0aCI6Ii83NTQzMDgzNi8yODY1ODMxNzAtYzM3NDVjZDUtNjFiNy00YTVlLWFiMDItMTM5MjZiNmM1Njc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE1MzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwYTlhZDYzNTFjNmNjMmE0ZDM4OTllODg5ODRhYjJmY2VjNzI2MjI4NmY3MTA0ZTMyODIyNDZkOTc1NDg1NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X68vaPnaaX_T6QS9tCIGb4amaKwW8B_qK2lVIDyAVXg)
> > > Strange, because before I turned on Fractional Scaling it was working like a charm, even my build (I changed Segoe with the new Aptos font).
> > 
> > 
> > Great, the source is the problem. I was already wanting to change it anyway.
> > As you can see, I am preparing version 5.0. There will be no changes to features, just a redesign of the app's appearance and a greater focus on multiple users.
> 
> Great. If you need testers, I am here. 😄

Just install manually and test!

https://github.com/zapzap-linux/zapzap/releases/tag/5.0-ALFA-2

**Comment by llsaboya** [comment]
Still no luck trying to figure out what is happening. I found a workaround for this issue here: https://bugreports.qt.io/browse/QTBUG-113574

`QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor`

![image](https://github.com/zapzap-linux/zapzap/assets/75430836/4998dba8-039a-4941-b153-348b6ee0eaef)

**Comment by rafatosta** [comment]
> Still no luck trying to figure out what is happening. I found a workaround for this issue here: https://bugreports.qt.io/browse/QTBUG-113574
> 
> `QT_SCALE_FACTOR_ROUNDING_POLICY=RoundPreferFloor`
> 
> I am using the lastest beta release.
> 
> ![image](https://private-user-images.githubusercontent.com/75430836/288931598-4998dba8-039a-4941-b153-348b6ee0eaef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDA2MDksIm5iZiI6MTcwMjAwMDMwOSwicGF0aCI6Ii83NTQzMDgzNi8yODg5MzE1OTgtNDk5OGRiYTgtMDM5YS00OTQxLWIxNTMtMzQ4YjZlZTBlYWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxNTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhOWFjMTc0ZDI1ZDA0M2U1NzI3OGI5ZjBkZjQ5Y2UxOTAwZGVkMzI1M2ZjOTdlY2NiMzY4ODI0Zjg2NjBkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e4vSuTPVRZ5k4W9GrtPGdRhi-OFKEdeRlBA3Pxy5fXE)

It seems to be a solution. I will insert this flag in the code. Thanks

**Comment by rafatosta** [comment]
Try https://github.com/zapzap-linux/zapzap/releases/tag/5.0-BETA-3

**Comment by llsaboya** [comment]
> Try https://github.com/zapzap-linux/zapzap/releases/tag/5.0-BETA-3

Didn't get the environment variable by default. I added it with Flatseal and is working.

![Captura de tela de 2023-12-13 10 09 55](https://github.com/zapzap-linux/zapzap/assets/75430836/6bec8600-4cd1-4f98-8037-7c1adacdb9f2)

**Comment by rafatosta** [comment]
The problem was resolved in the last update

**Comment by llsaboya** [comment]
Sorry for the delay in responding. I got stuck in the X11 of Ubuntu for the last two weeks.

The variable does not appear in FlatPak yet. After I fix in Flatsal,  it looks normal.

![zapzap-fs](https://github.com/zapzap-linux/zapzap/assets/75430836/8cb5aa45-8b06-417e-9cdc-53891b3fa799)

![zapzap-fs-1](https://github.com/zapzap-linux/zapzap/assets/75430836/1ae40535-f41e-4e48-9888-5b2e1d71c977)

**Comment by rafatosta** [comment]
> Sorry for the delay in responding. I got stuck in the X11 of Ubuntu for the last two weeks.
> 
> The variable does not appear in FlatPak yet. After I fix in Flatsal, it looks normal.
> 
> ![zapzap-fs](https://private-user-images.githubusercontent.com/75430836/292888009-8cb5aa45-8b06-417e-9cdc-53891b3fa799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2Mzg5MzEsIm5iZiI6MTcwMzYzODYzMSwicGF0aCI6Ii83NTQzMDgzNi8yOTI4ODgwMDktOGNiNWFhNDUtOGIwNi00MTdlLTljZGMtNTM4OTFiM2ZhNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAwNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNzk1MTdmODBlNmEzMTZlY2Y2NDhmYWVkYjNmYWJjMGUwNjExZTRiNDEzMjZjMGFhODhjNWYzYjdiZDM4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P2oiNk693wCLCkNi83LbODgnwGJiiA044XsUPNHtthc)
> 
> ![zapzap-fs-1](https://private-user-images.githubusercontent.com/75430836/292888017-1ae40535-f41e-4e48-9888-5b2e1d71c977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2Mzg5MzEsIm5iZiI6MTcwMzYzODYzMSwicGF0aCI6Ii83NTQzMDgzNi8yOTI4ODgwMTctMWFlNDA1MzUtZjQxZS00ZTQ4LTk4ODgtNWIyZTFkNzFjOTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDAwNTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMjkyYTA1MTYxMDc4OTczYmY5OWI5ZDdjYTQ3MTQyYmVmYzZkNzM5YjI5Njc0MjQxMTg0NTM3NTgzZTBlZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UIXxjOcpAFFsFIBI4-vUNsSNpAaQ8Lay_L-vixce9tk)

I am directly setting the configuration in the application. However, it seems that the flatpak ignores it. Anyway, I'll put it as a flag in the flatpak. Thanks for the feedback

**Comment by rafatosta** [comment]
Você é brasileiro!! Agora que notei o texto dos prints 🤣🤣
Abraços

**Comment by llsaboya** [comment]
> Você é brasileiro!! Agora que notei o texto dos prints 🤣🤣 Abraços

Sim, sou. Mas escrevi em inglês porque vai que alguém tenha o mesmo problema. Fiquei um tempão sem usar o ZapZap por causa disso mesmo precisando para minhas duas contas de WhatsApp. 

Então, no melhor espírito FOSS, resolvi tentar ajudar a achar uma solução com minhas próprias mãos: ou seja, usando muuuiiito o google porque eu não tenho muita certeza do que estou fazendo. 😄

**Comment by rafatosta** [comment]
Compilei com a tag e você poderá testar aqui: https://github.com/zapzap-linux/zapzap/releases/tag/5.1
![image](https://github.com/zapzap-linux/zapzap/assets/18619894/20828732-9bb0-4448-b162-a4f08947b991)

Depois solto a atualização para o flathub.

**Comment by llsaboya** [comment]
Feito! Agora pegou a variável.

![image](https://github.com/zapzap-linux/zapzap/assets/75430836/29097ae1-887f-4b03-b07b-c7bf46858b30)
