### ISSUE TITLE
[Feature] Add keyboard shortcut to close window (to tray)

### ISSUE THREAD

**Issue by danielwillms** [zapzap-linux/zapzap#26]
I was wondering if it was possible to add a keyboard shortcut to hide/close the window?
I know that it's possible to hard-close it with Ctrl+Q, but I'd like to "close" it to the tray.
For instance Telegram uses Ctrl+W to hide to tray icon!

**Comment by rafatosta** [comment]
Hello, Ctrl+W has already been implemented to hide the window. Wait or follow the news through the Beta builds in Releases

**Comment by danielwillms** [comment]
Ahh, I didn't find it in the changelogs, but I just installed Version 5 Beta 3, it works great, thanks!

**Comment by rafatosta** [comment]
> Ahh, não encontrei nos changelogs, mas acabei de instalar a versão 5 Beta 3, funciona muito bem, obrigado!

It has been implemented for 3 weeks. Finally, test and report the problems found. Thank you very much for your collaboration
