### ISSUE TITLE
Allow hiding vertical toolbar in the left side.

### ISSUE THREAD

**Issue by volanin** [zapzap-linux/zapzap#29]
Hello, in the new version of zapzap there is a vertical toolbar in the left side. This toolbar makes it easy to switch between multiple accounts, but since I don't use multiple accounts (and I believe most people don't), this toolbar is quite useless and takes precious space in low resolution monitors like mine (1366x768 on a DELL notebook).

I'd love an option to allow hiding this toolbar, so the interface looks the same as the previous versions.

**Comment by rafatosta** [comment]
It will arrive very soon. I don't use it either 😅
