### ISSUE TITLE
Notifications don't show on any device while Zapzap is running

### ISSUE THREAD

**Issue by sohxet** [zapzap-linux/zapzap#3]
Expected behaviour:     Notifications for messages and calls sound and appear on all devices. 

Actual behaviour:           For messages, only Zapzap plays a sound and no devices show a notification. Calls come in normally on the phone but the tablet doesn't notify at all if Zapzap is running, and Xapzap doesn't notify either, but the "missed call" notification does appear on the tablet if the call is dropped. When whatsapp is open on the tablet and there's an incoming call it does show the notification, but Zapzap still doesn't notify when it's open. 

Steps to recreate:           Install Zapzap from flathub, link tablet and zapzap to phone's whatsapp, wait for an incoming message or call.

Phone and tablet:          Official app v2.23.20.76, currently latest non-beta
Zapzap:                            v4.5.3, currently lastest on flathub
OS:                                    Nobara 36 (Fedora based)
DE:                                    Gnome 42
Windowing:                     X11   

------------------

Hey, that's everything I could think to test. Other than this notification thing Zapzap works great and I really like using it.
Cheers

**Comment by rafatosta** [comment]
Please, make sure this behavior happens when using Whatsapp Web.

**Comment by o0nd7ots** [comment]
I am unable to reproduce this
