### ISSUE TITLE
[Feature] Send message to non-contact phone number

### ISSUE THREAD

**Issue by serhumanos** [zapzap-linux/zapzap#30]
I like to be able to send messages to a phone number that is not present in my contacts.
I see this option in others whatsapp web containers, using whatsapp web link reference to new number.

Thanks for your great app! is the best

**Comment by rafatosta** [comment]
This function already exists. I still need to adjust some things, but you can use the shortcut Ctrl+N

**Comment by serhumanos** [comment]
> This function already exists. I still need to adjust some things in user interface, but you can use the shortcut Ctrl+N

Nice! I recently update to v5 (I had to remove and reinstall to do it correctly) and I had the idea that this option was in previous version.
Thanks again for your quick reply! greetings!
