### ISSUE TITLE
Zapzap asks to update browser

### ISSUE THREAD

**Issue by thgdorns** [zapzap-linux/zapzap#31]
Hello,

I inadvertently opened two instances of Zapzap, and now I can't log into my main account. The following message is displayed. I tried reloading the page, but to no avail.

![image](https://github.com/zapzap-linux/zapzap/assets/61665381/2405219d-f6b2-4d74-b438-0825d9cd81cb)

I created another user and was able to login, but I can't delete the main account, which shows the aforementioned message.

**Comment by rafatosta** [comment]
This happens sometimes and it's WhatsApp web's fault. There are two simple solutions, pressing F5 until it works or closing the app and opening it again. 

I'm studying a way to get around this problem.

**Comment by rafatosta** [comment]
This happens sometimes and it's WhatsApp web's fault. There are two simple solutions, pressing F5 until it works or closing the app and opening it again. 

I'm studying a way to get around this problem.

**Comment by rafatosta** [comment]
This version of yours is out of date. Please use the latest version

**Comment by thgdorns** [comment]
I restarted Zapzap and problem was solved. Thank you.
