### ISSUE TITLE
german translation is unused

### ISSUE THREAD

**Issue by Laserlicht** [zapzap-linux/zapzap#33]
At least it's not translated in my Linux Mint.

Also de.po doesn't seems to updated anymore.

**Comment by rafatosta** [comment]
For other languages, I need users' collaboration to keep them up to date. You can update the translations and make a request pull from the following file: [de.po](https://github.com/zapzap-linux/zapzap/blob/main/po/de.po)

Thank you very much

**Comment by Laserlicht** [comment]
The file was already translated. But I've found a syntax error. Maybe this was the problem...
