### ISSUE TITLE
Flatpak issues

### ISSUE THREAD

**Issue by o0nd7ots** [zapzap-linux/zapzap#37]
# Intro
Since the app is oficially provided as a flatpak, I felt like making this issue to talk about what could be better with especially the flatpak stuff.

# Current list
As of right now, some things come to my mind:
## Filesystem
I think that the app does not need the access to *All system files* -- that just makes using the sandbox useless.

I have tested it limiting the filesystem access with Flatseal and I have slimmed it down to just the `xdg-config` permission (`~/.config` in my case) and the app still launches

Also we can consider `ro` and `create` where posssible for the permissions.
## Portals
1. On the website we advertise that ZapZap can run in the background, but it does not have access to the Background portal.
2. On the website we advertise that ZapZap can send native notifications, but it does not have access to the Notifications portal. Instead it **Talks** to `org.freedesktop.Notifications**. I think moving that to Portals permission would also help.
## Device
I understand the GPU acceleration, but do we need All Devices? If we need a camera or microphone, could we also move that to Portals?
## Packaging
The version seems inconsistent: Version is 5.1.1 but the Subject says `:bookmark: 5.2-1. Is it supposed to be like that?
```
 $ flatpak info com.rtosta.zapzap

ZapZap - WhatsApp Messenger

          ID: com.rtosta.zapzap
         Ref: app/com.rtosta.zapzap/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 5.1.1
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 253,2 MB
     Runtime: org.kde.Platform/x86_64/6.6
         Sdk: org.kde.Sdk/x86_64/6.6

      Commit: 222ee1cfbb06b0e34ce94d8a62204caf85ea83076c327f9ae5c828aca235452e
      Parent: 08b24a36e2e75c0402e2d8388cd8dbf805befdbb5402e8b43601abd5bb32bd92
     Subject: :bookmark: 5.1-2 (d6664427)
        Date: 2024-01-07 13:33:17 +0000
```
# General questions
1. What is *shared inter-process communications*? If I turn it off the app starts I guess that breaks something that I do not notice.
2. Where can I change the flatpak stuff?
    I have seen the [yaml file used to generate the flatpak](https://github.com/flathub/com.rtosta.zapzap/blob/master/com.rtosta.zapzap.yaml) (at least I think so), but I get an error when I try to edit it on github.

**Comment by rafatosta** [comment]
### Filesystem
Yes. Permission is required to all files on the computer.

 For lay users, who do not know about pensions and flatseal, will not be able to share files from any storage device on the computer. Thus assuming the application learns failures.

### Portals
The background portal is new and I couldn't stop to study it.
 For notifications I use DBUS, which generates native notifications. It could be replaced, but Zapzap is also executed outside Flatpak and I don't know the portal's compatibility outside Sandbox.

 Anyway, I would love a contribution in this regard.

### Device
Zapzap encapsulates the WhatsApp Web, so all access to the camera and microphone is the responsibility of the QT. The QT makes use and manages these features optimally, requiring only FLATPAK access permission through the Yaml file.


### General questions

1 - I did not understand
2 - See https://github.com/zapzap-linux/zapzap/tree/main/_packaging/flatpak

About the version, it's just that I changed the name of the version.

**Comment by o0nd7ots** [comment]
> ### Filesystem
> 
> For lay users, who do not know about permission and flatseal, will not be able to share files from any storage device on the computer. Thus assuming the application learns failures.

Okay, I can see that. Using the file picker portal would just solve this, but it seems neither you nor I can implement it yet.

I think that most users will be sharing files from their `/home/user` directory, so I think we could change the permissions to that.
Also, if the permission is needed just for sharing files, I think we could use the read only option, so that the app cannot modify the files. (Yes, I know this is just a whatsapp client but I am trying to follow best practices)

What I suggest for now is:
- `xdg-config/app-config` - RW
- `xdg-home` - RO
- `xdg-download` - Create
- the rest as it is.
> ### Portals

I see. Thank you for explaining
> ### Device
> [...] requiring only FLATPAK access permission through the Yaml file.

What do you mean?
> ### General questions
> 1 - I did not understand 

On the project's website it says that ZapZap can run in the background.
![image](https://github.com/zapzap-linux/zapzap/assets/124466962/0a44bb75-3652-4e52-93d5-3bf8a2f46a4c)
I just noticed that the flatpak package does not have access to the Background portal.

> 2 - See https://github.com/zapzap-linux/zapzap/tree/main/_packaging/flatpak

Thanks!

**Comment by rafatosta** [comment]
> > ### Filesystem
> > 
> > For lay users, who do not know about permission and flatseal, will not be able to share files from any storage device on the computer. Thus assuming the application learns failures.
> 
> Okay, I can see that. Using the file picker portal would just solve this, but it seems neither you nor I can implement it yet.
> 
> I think that most users will be sharing files from their `/home/user` directory, so I think we could change the permissions to that.
> Also, if the permission is needed just for sharing files, I think we could use the read only option, so that the app cannot modify the files. (Yes, I know this is just a whatsapp client but I am trying to follow best practices)
> 
> What I suggest for now is:
> - `xdg-config/app-config` - RW
> - `xdg-home` - RO
> - `xdg-download` - Create
> - the rest as it is.
> > ### Portals
> 
> I see. Thank you for explaining
> > ### Device
> > [...] requiring only FLATPAK access permission through the Yaml file.
> 
> What do you mean?
> > ### General questions
> > 1 - I did not understand 
> 
> On the project's website it says that ZapZap can run in the background.
> ![image](https://github.com/zapzap-linux/zapzap/assets/124466962/0a44bb75-3652-4e52-93d5-3bf8a2f46a4c)
> I just noticed that the flatpak package does not have access to the Background portal.
> 
> > 2 - See https://github.com/zapzap-linux/zapzap/tree/main/_packaging/flatpak
> 
> Thanks!
> 

I've already done all this analysis of permissions. Even doing what is "recommended", I received several reports that the app was not working as it should. 

The conclusions I reached were: most Linux users are unaware of permissions; and I must deliver the app with all features fully working. 

If any user is not comfortable with the permissions, they have every right to make their own changes through Flatseal.

Running in the background is just the option to close the window and continue receiving notifications. Remember, ZapZap is just a capsule for Whatsapp Web.

**Comment by o0nd7ots** [comment]
I understand your point.

Do you think that a file picker portal could be added as a far roadmap goal?
