### ISSUE TITLE
Hide sidebar when window is narrow

### ISSUE THREAD

**Issue by antrmn** [zapzap-linux/zapzap#41]
It would be really nice to have the sidebar to disappear when the window is too narrow. This responsive layout would allow to easily have ZapZap as a side window in a tiling WM.

There are some custom CSS for Stylus (the Firefox extensions) that allow this, but I can't manage to find them anymore.

**Comment by rafatosta** [comment]
I didn't find this extension.
I will not add this option. So I would imply change WhatsApp web and intend to keep it without my interference.

**Comment by antrmn** [comment]
Any indication on how one can possibly edit the CSS inside ZapZap?

**Comment by rafatosta** [comment]
> Any indication on how one can possibly edit the CSS inside ZapZap?

Just inject JavaScript codes into https://github.com/zapzap-linux/zapzap/blob/main/zapzap/engine/whatsapp.py

In the file itself you find examples of how I execute JavaScript codes within whatsapp
