### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by farid220** [zapzap-linux/zapzap#42]
Hi
I'd created the same topic in previous repo but as it got archived, I'm reposting.

First of all thanks for this great application this has been really useful since there is no official application for WhatsApp.
I was wondering if you could add Socks5 - HTTP/HTTPS proxy support.
WhatsApp is blocked in some regions like Iran and ofc many of VPN Protocols that support Tunnel Adapters are blocked too (OpenVPN - Wireguard - ....)

Setting system proxy doesn't work.

**Comment by rafatosta** [comment]
Download in:
https://github.com/zapzap-linux/zapzap/releases/tag/proxysuport

Make a manual installation with Flatpak Install.

At the moment I did through the terminal for testing only.
To execute do:
`flatpak run com.rtosta.zapzap --setType Socks5Proxy --setHostName MyHost --setPort 0201 --setUser Myuser --setPassword 123456`

Replace values or remove options that are not required for you.

**Comment by rafatosta** [comment]
The types are:

- DefaultProxy
- Socks5Proxy
- HttpProxy

**Comment by rafatosta** [comment]
> > The types are:
> > ```
> > * DefaultProxy
> > 
> > * Socks5Proxy
> > 
> > * HttpProxy
> > ```
> 
> Hi Thanks for taking the trouble of adding the proxy feature I installed the custom version of "proxysupport" branch and it works perfectly. I tested all three options and "HttpProxy" and "Socks5Proxy" worked perfectly but I couldn't connect using "DefaultProxy" type. I might be using it wrong. Here is the command I'm using: flatpak run com.rtosta.zapzap --setType DefaultProxy
> 
> I have set the network proxy in my Fedora so I assumed it doesn't need any other parameters like "--setHostName" or "--setPort". Also I think "--setHostName" should support both IP address and hostname. I wasn't able to connect using 127.0.0.1 IP.
> 
> I'd appreciate it if you could merge it into the main branch so we could download it directly through Flathub. I think adding an option in UI in setting would be a better option rather than commandline.
> 
> Thanks again.

Great that it works. I will merge it and then adjust as necessary. Thanks for the feedback

**Comment by rafatosta** [comment]
@farid220 
These are the options available for proxy:
https://doc.qt.io/qt-6/qnetworkproxy.html#ProxyType-enum

I will make them all available in the full implementation
