### ISSUE TITLE
Issue while saving files in zapzap

### ISSUE THREAD

**Issue by oshaileshmohan** [zapzap-linux/zapzap#43]
Hi Team,

I would like to report an issue while saving/download data in our local system while using zapzap. WHile saving data it should pickup the filename automatically which is not happening. Apart from this, your app is awsome.

**Comment by rafatosta** [comment]
This problem started to bother me too ... I will look for a solution soon. Thanks for the collaboration!

**Comment by vvch** [comment]
It bothers metoo :(
