### ISSUE TITLE
[Feature Request] Custom Chat Background

### ISSUE THREAD

**Issue by hideki2k02** [zapzap-linux/zapzap#44]
Hello e boa noite.

It would be interesting (not necessarely useful haha) to have a feature that would allow Custom Background Images.

**Comment by rafatosta** [comment]
Boa noite. Essa funcionalidade existe. Vá nas configurações do Whatsapp Web a partir do painel de configurações na seção Geral ou diretamente no menu do chat.

**Comment by hideki2k02** [comment]
Então até tem os bagulho de corzinha, mas não tem como colocar Imagem como Plano de Fundo? Já vi algumas Extensões que fazem isso

**Comment by rafatosta** [comment]
> Então até tem os bagulho de corzinha, mas não tem como colocar Imagem como Plano de Fundo? Já vi algumas Extensões que fazem isso

Verdade. Achei que possuía a opção de colocar fotos. 
De qualquer forma, não adicionarei essa opção. Pois, implicaria em alterar o WhatsApp Web e pretendo mantê-lo sem minha interferência.
