### ISSUE TITLE
[Feature] Ability to customize colors independently of each account

### ISSUE THREAD

**Issue by Serg10** [zapzap-linux/zapzap#47]
Please, add the ability to customize colors independently of each account or simply change theme separately on each account.

**Comment by rafatosta** [comment]
What do you mean by "colors"? 

What's the point of using a theme with dark and another with light?

**Comment by Serg10** [comment]
colors = customize appearance

The reason is to quickly distinguish which account you are on.
This is because I use two accounts (work and personal) but the contacts are shared between the two accounts and I don't want to get confused and send messages from the wrong account.
In Windows I already do it, I open WhatsApp web in different browsers and each one has its own custom colors.

**Comment by rafatosta** [comment]
> colors = customize appearance
> 
> The reason is to quickly distinguish which account you are on. This is because I use two accounts (work and personal) but the contacts are shared between the two accounts and I don't want to get confused and send messages from the wrong account. In Windows I already do it, I open WhatsApp web in different browsers and each one has its own custom colors.

There is a flag next to the current account!
![image](https://github.com/zapzap-linux/zapzap/assets/18619894/07cc37e3-6fb3-4c3f-bdf1-54925b6ea39e)

**Comment by Serg10** [comment]
I know, the color of the flag is different, but the color, appearance, background, theme, chat, everything else... is the same on both accounts.

**Comment by rafatosta** [comment]
> I know, the color of the flag is different, but the color, appearance, background, theme, chat, everything else... is the same on both accounts.

You can change the chat background.
