### ISSUE TITLE
--hidestart flag is causing a notification every single time

### ISSUE THREAD

**Issue by BaconCatBug** [zapzap-linux/zapzap#48]
I run ZapZap on system boot via the following command `flatpak run com.rtosta.zapzap --hideStart`
However, as of 5.1.1, running with this flag causes a notification about running in the background. How can I prevent this notification from happening every single time? 
![image](https://github.com/zapzap-linux/zapzap/assets/4897163/267bce02-da21-430c-9b97-c2109c0ab7b3)

**Comment by rafatosta** [comment]
> I run ZapZap on system boot via the following command `flatpak run com.rtosta.zapzap --hideStart`
> However, as of 5.1.1, running with this flag causes a notification about running in the background. How can I prevent this notification from happening every single time? 
> ![image](https://github.com/zapzap-linux/zapzap/assets/4897163/267bce02-da21-430c-9b97-c2109c0ab7b3)
> 

It's just an execution warning message. I will soon add an option to disable it if you want.
