### ISSUE TITLE
System tray icon not visible

### ISSUE THREAD

**Issue by NandiyaLive** [zapzap-linux/zapzap#5]
System tray icon is not visible, but can be clicked.

OS : Manajro Linux
Version :  4.5.2-1 (AUR)

**Comment by rafatosta** [comment]
Please see this warning [#6 ](https://github.com/zapzap-linux/zapzap/issues/6)

**Comment by NandiyaLive** [comment]
Tried building from the source, but still not working.

**Comment by igoutta** [comment]
Same issue in Arch building from the source. The program closes but doesn't show as background app, but stills runs in the background, leading to waste RAM.

**Comment by rafatosta** [comment]
I believe this is the real problem #9. 
And so it is not showing the icon in the system tray.

**Comment by NandiyaLive** [comment]
> I believe this is the real problem #9. And so it is not showing the icon in the system tray.

Yeah that's the problem

**Comment by NandiyaLive** [comment]
Found a workaround to fix this problem on this [Reddit comment](https://www.reddit.com/r/ManjaroLinux/comments/ueil3i/comment/i6nlk9t/?utm_source=share&utm_medium=web2x&context=3)

- Install the application 'qt6ct' and run it, make sure to select an icon theme
- In a terminal, run 'QT_QPA_PLATFORMTHEME=qt6ct zapzap'
