### ISSUE TITLE
Submenu in dark mode is white on white

### ISSUE THREAD

**Issue by mielouk** [zapzap-linux/zapzap#50]
Hello,

since a few weeks I've been using zapzap and I'm quite satisfied with its general performance. Though I've a few little things that don't work right (yet).

General information:

zapzap 5.1-1 installed via the AUR on Manjaro
up to date Manjaro install
Sway Window Manager (thus Wayland active and confirmed with xeyes that zapzap is working with Wayland) 

Issue:

![submenu zapzap](https://github.com/zapzap-linux/zapzap/assets/3057062/64d9d736-9d2f-4654-be68-68f98a7a1e27)

Please let me know if you need further information!

**Comment by rafatosta** [comment]
> Hello,
> 
> since a few weeks I've been using zapzap and I'm quite satisfied with its general performance. Though I've a few little things that don't work right (yet).
> 
> General information:
> 
> zapzap 5.1-1 installed via the AUR on Manjaro
> up to date Manjaro install
> Sway Window Manager (thus Wayland active and confirmed with xeyes that zapzap is working with Wayland) 
> 
> Issue:
> 
> ![submenu zapzap](https://github.com/zapzap-linux/zapzap/assets/3057062/64d9d736-9d2f-4654-be68-68f98a7a1e27)
> 
> 
> Please let me know if you need further information!

Does this happen when using Zapzap on flatpak?

**Comment by rafatosta** [comment]
To look #6

**Comment by mielouk** [comment]
> To look #6

OK, will try flatpak version.
