### ISSUE TITLE
ZapZap gets unresponsive after checking info of message after long textfield is extended

### ISSUE THREAD

**Issue by mielouk** [zapzap-linux/zapzap#51]
General information:

zapzap 5.1-1 installed via the AUR on Manjaro
up to date Manjaro install
Sway Window Manager (thus Wayland active and confirmed with xeyes that zapzap is working with Wayland)

Issue:

When I post a long message that is longer than the maximum standard length of a text field in WA, I've to extend the field by clicking 'read more' ( in the picture 'Mehr lesen') to be able to read the rest of the posted message.

![2024-02-09-165846_grim](https://github.com/zapzap-linux/zapzap/assets/3057062/9d6cab1a-4e4d-42c1-a1fd-06fca02c4822)

When I try to get the info on who has read the message by clicking 'Nachrichteninfo' after I extended the message, ZapZap completely freezes and I've to pkill it and restart/reconnect the whole program.

![2024-02-09-165953_grim](https://github.com/zapzap-linux/zapzap/assets/3057062/33091df1-cb33-40c4-8e90-b141fa29dc05)

**Comment by rafatosta** [comment]
> General information:
> 
> zapzap 5.1-1 installed via the AUR on Manjaro
> up to date Manjaro install
> Sway Window Manager (thus Wayland active and confirmed with xeyes that zapzap is working with Wayland)
> 
> Issue:
> 
> When I post a long message that is longer than the maximum standard length of a text field in WA, I've to extend the field by clicking 'read more' ( in the picture 'Mehr lesen') to be able to read the rest of the posted message.
> 
> ![2024-02-09-165846_grim](https://github.com/zapzap-linux/zapzap/assets/3057062/9d6cab1a-4e4d-42c1-a1fd-06fca02c4822)
> 
> When I try to get the info on who has read the message by clicking 'Nachrichteninfo' after I extended the message, ZapZap completely freezes and I've to pkill it and restart/reconnect the whole program.
> 
> ![2024-02-09-165953_grim](https://github.com/zapzap-linux/zapzap/assets/3057062/33091df1-cb33-40c4-8e90-b141fa29dc05)
> 
> 

The same thing happened to me. I will analyze and try to resolve

**Comment by rafatosta** [comment]
This is not a Zapzap problem, but from WhatsApp Web. Because the same happens with WhatsApp Web!

**Comment by mielouk** [comment]
Should I report this bug at Meta?

**Comment by rafatosta** [comment]
> Should I report this bug at Meta?

Yes!!

**Comment by rafatosta** [comment]
Fix by the Meta
