### ISSUE TITLE
White on white still present

### ISSUE THREAD

**Issue by mielouk** [zapzap-linux/zapzap#52]
Sorry to bother you again. The issue I mentioned earlier in [this report](https://github.com/zapzap-linux/zapzap/issues/50) is still present. Now with flatpak version 5.1 its the same issue. Saw that the flatpak version pull some KDE/Qt dependencies. This might be why this doesn't work properly in a GTK environment.

![whiteonwhiteissue](https://github.com/zapzap-linux/zapzap/assets/3057062/ddebd11e-7475-4d10-8a53-733fe660fe55)

**Comment by rafatosta** [comment]
> Sorry to bother you again. The issue I mentioned earlier in [this report](https://github.com/zapzap-linux/zapzap/issues/50) is still present. Now with flatpak version 5.1 its the same issue. Saw that the flatpak version pull some KDE/Qt dependencies. This might be why this doesn't work properly in a GTK environment.
> 
> ![whiteonwhiteissue](https://github.com/zapzap-linux/zapzap/assets/3057062/ddebd11e-7475-4d10-8a53-733fe660fe55)
> 

I'll analyze it to see if it's on the app side. I use Gnome and there is no such thing.

**Comment by mielouk** [comment]
> I'll analyze it to see if it's on the app side. I use Gnome and there is no such thing.

Could it be that I've to set some environment variable with regard to Qt?

**Comment by mielouk** [comment]
Thank you for your fast responses!

When may I expect these changes in the flatpak version?

**Comment by mielouk** [comment]
Thank you!
