### ISSUE TITLE
Quebrando o sistema quando clica 2x em tema ( quando usando wayland) 

### ISSUE THREAD

**Issue by Mazuricio** [zapzap-linux/zapzap#54]
Caso esteja usando o wayland como sistema de janela, ao abrir as configurações e ir em temas, você clicando 2 vezes na barra de seleção ele quebra a sessão e retorna para a tela de login

Alterei o Flatseal para usar o x11, mesmo estando em uma sessão wayland, e não ocorre, talvez seja problema com o QT em si.

Uso Pop!_OS 22.04, sessão wayland, zapzap flatpak

**Comment by rafatosta** [comment]
Cara, não consegui reproduzir esse problema utilizando o wayland.

[Gravação de tela de 2024-02-20 08-58-23.webm](https://github.com/zapzap-linux/zapzap/assets/18619894/7b3bb741-40f3-42f9-95ae-7b0c6caa414a)
