### ISSUE TITLE
[FEATURE] Add support for notification count badge

### ISSUE THREAD

**Issue by kurokid** [zapzap-linux/zapzap#59]
Hello,
Can you please add support for notification count badge on panel/dock like for kde plasma taskbar or dock in elementaryos.
Image just for reference
![image](https://github.com/zapzap-linux/zapzap/assets/4388301/fdc022e9-3ecd-4764-a4a0-37b5baa668d1)

Link for reference [https://wiki.ubuntu.com/Unity/LauncherAPI#Low_level_DBus_API:_com.canonical.Unity.LauncherEntry](url). It can use libunity or low level dbus API.

**Comment by rafatosta** [comment]
Look in https://wiki.ubuntu.com/Unity/LauncherAPI#Low_level_DBus_API:_com.canonical.Unity.LauncherEntry
 **_While the libunity API is stable, the DBus protocol underneath is not. We strongly discourage anyone from relying on it._**
