### ISSUE TITLE
Autostart no longer works

### ISSUE THREAD

**Issue by dm30** [zapzap-linux/zapzap#61]
I don't know what's been the change, but after  flawless operation, ZapZap no longer auto-starts when logging into system (Zorin OS 17, and Ubuntu 23.10 too) 
Thanks in advance.

**Comment by rafatosta** [comment]
It was really broken, but correcting and launched a version yesterday. Check if it is up to date, please
![image](https://github.com/zapzap-linux/zapzap/assets/18619894/a9522f77-f63c-4c2c-abd8-2a6661ca8344)

**Comment by dm30** [comment]
Yes! I already noticed in the evening (Greenwich +1 time) but I just wanted to try out a little more. Seems to be fixed. Thank you.
