### ISSUE TITLE
zapzap on KDE Plasma 6 and Qt6

### ISSUE THREAD

**Issue by hsantanna** [zapzap-linux/zapzap#62]
zapzap wont open anymore after updating to KDE Plasma 6.

I'm getting this error:

Traceback (most recent call last):
File "/usr/bin/zapzap", line 33, in <module>
sys.exit(load_entry_point('zapzap==5.0', 'gui_scripts', 'zapzap')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/bin/zapzap", line 25, in importlib_load_entry_point
return next(matches).load()
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
module = import_module(match.group('module'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/usr/lib/python3.11/site-packages/zapzap/__main__.py", line 3, in <module>
from zapzap.controllers.SingleApplication import SingleApplication
File "/usr/lib/python3.11/site-packages/zapzap/controllers/SingleApplication.py", line 1, in <module>
from PyQt6.QtWidgets import QApplication
ImportError: /usr/lib/python3.11/site-packages/PyQt6/QtGui.abi3.so: undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6

**Comment by rafatosta** [comment]
> zapzap wont open anymore after updating to KDE Plasma 6.
> 
> I'm getting this error:
> 
> Traceback (most recent call last):
> File "/usr/bin/zapzap", line 33, in <module>
> sys.exit(load_entry_point('zapzap==5.0', 'gui_scripts', 'zapzap')())
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/bin/zapzap", line 25, in importlib_load_entry_point
> return next(matches).load()
> ^^^^^^^^^^^^^^^^^^^^
> File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
> module = import_module(match.group('module'))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
> File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
> File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
> File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> File "/usr/lib/python3.11/site-packages/zapzap/__main__.py", line 3, in <module>
> from zapzap.controllers.SingleApplication import SingleApplication
> File "/usr/lib/python3.11/site-packages/zapzap/controllers/SingleApplication.py", line 1, in <module>
> from PyQt6.QtWidgets import QApplication
> ImportError: /usr/lib/python3.11/site-packages/PyQt6/QtGui.abi3.so: undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6

Qual distribuição? Isso é uma execução em Flatpak?

**Comment by hsantanna** [comment]
Arch Linux, do aur: https://aur.archlinux.org/packages/zapzap

O Plasma 6 foi lançado ontem (2024-02-28), nesse momento a versão final está disponível no extra-testing do Arch.

**Comment by hsantanna** [comment]
Creio que o problema seja em relação a minha versão do Qt6 (6.7.0beta3-1), aparentemente há um recurso que não é mais oferecido nesta versão 6.7 e que é necessário ao zapzap.

De todo modo agradeço a atenção, vou procurar por uma forma de contornar, caso contrário usarei o flatpak.

**Comment by hsantanna** [comment]
Fazer o downgrade do Qt6 para 6.6.2 resolveu o problema.

**Comment by rafatosta** [comment]
> Creio que o problema seja em relação a minha versão do Qt6 (6.7.0beta3-1), aparentemente há um recurso que não é mais oferecido nesta versão 6.7 e que é necessário ao zapzap.
> 
> De todo modo agradeço a atenção, vou procurar por uma forma de contornar, caso contrário usarei o flatpak.

Por que não usar em flatpak e pronto? Às vezes acho que alguns usuários do Arch gostam de complicar as coisas e querer tudo em AUR 😅

Ah, esse seu tipo de problema foi um dos motivos por não mantê-lo oficialmente no AUR, não tenho como controlar o que o usuário tem instalado.

**Comment by rafatosta** [comment]
Note também que, a versão do zapzap no AUR está desatualizada!
