### ISSUE TITLE
Add the hability to customize shortcuts

### ISSUE THREAD

**Issue by tarsobcaldas** [zapzap-linux/zapzap#66]
I'm very used to Ctrl+w as delete word (ctrl+backspace), but in the program it is set as close window. It would be nice to be able to customize the program's shortcut so it doesn't interfere with with that.

**Comment by rafatosta** [comment]
Ctrl+W hides the window. This behavior is common on Telegram and kept to make it more like other apps.

**Comment by rafatosta** [comment]
You can use Ctrl+Shift+Arrow to select only one word
