### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [zapzap-linux/zapzap#68]
Can you verify the flatpak so that people who find it through Flathub know it is official? Here's a link to Flathub's verification documentation for developers https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by prodrigestivill** [comment]
To validate using the current id `com.rtosta.zapzap` you need to own the domain `rtosta.com`.
Once you own the domain, you have to setup some hosting and then you can upload the file requested by flathub webpage to allow the validation.

Alternatively the flatpak `appid` can be renamed to `io.github.zapzap-linux.ZapZap` and validated using the flathub webpage.
To rename the flatpak, first request to create the new app to flathub using the new flatpak `appid`, then mark the old one [as stated here](https://docs.flathub.org/docs/for-app-authors/maintenance#end-of-life-rebase).
