### ISSUE TITLE
Sugestão de logo

### ISSUE THREAD

**Issue by dinhokusanagi** [zapzap-linux/zapzap#7]
OBS: É meramente opinião pessoal não se trata em denegrir ou diminuir o projeto 

O logo o zap zap é um pouco distante do que se parece o aplicativo e existe temas interessantes como este que eu vi na internet, tenho certeza que a escolha do logo foi algo muito bem pensado, mas da uma cara nova ao projeto pode ser bom as vezes.
https://stock.adobe.com/br/images/whatsapp-icon-logo-vector-on-white-background/510628157

![Screenshot_20231029_124428](https://github.com/zapzap-linux/zapzap/assets/43162113/71c5256e-cfce-4e82-a28f-65a0de94d0f8)

Olá. Agradeço a sugestão.
A logo do ZapZap foi construída de forma a ser uma identidade para o aplicativo. Ou seja, algo único e associado com o app - a pessoa olha para o ícone e sabe de qual aplicativo se trata. 
Não planejo utilizar ícones prontos da internet, mas aceito sugestões de ícones autorais e assim poder dar uma cara nova ao projeto.

Abraços

**Comment by rafatosta** [comment]
Você pode verificar toda a discussão anterior na construção da logo atual aqui: [Design a new icon for ZapZap]( https://github.com/rafatosta/zapzap/issues/70)
