### ISSUE TITLE
[Feature Request] Adicionar shortcut para atualizar página

### ISSUE THREAD

**Issue by JGMelon22** [zapzap-linux/zapzap#70]
### Cenário
Existem situações em que o WebView pode travar ao carregar as mensagens, especialmente quando uma instância do WhatsApp Web não é aberta por um certo tempo, o que ocasiona em acumular N mensagens.

### Sugestão
Adicionar um short cut para forçar o recarregamento da página. Ex: Ctrl + R

**Comment by rafatosta** [comment]
> ### Cenário
> Existem situações em que o WebView pode travar ao carregar as mensagens, especialmente quando uma instância do WhatsApp Web não é aberta por um certo tempo, o que ocasiona em acumular N mensagens.
> 
> ### Sugestão
> Adicionar um short cut para forçar o recarregamento da página. Ex: Ctrl + R
> 

O F5 faz justamente isso. Não está funcionando?

**Comment by JGMelon22** [comment]
Caramba, eu sou leigo demais 😂
Obrigado, Rafa. Fechando o issue agora
