### ISSUE TITLE
Document Phone Requirement (Required or not?)

### ISSUE THREAD

**Issue by maltfield** [zapzap-linux/zapzap#73]
This issue is an attempt to address the obvious question: does this `zapzap` serve as an *alternative* to the WhatsApp app (ie: "is it a standalone desktop app?") or is it just yet-another-second-class-desktop-client that routes messages through the phone on the intranet?

### Solution

This is not a support request. This is a ticket to update the documentation. Please do *not* answer this question just on this GitHub issue.

The solution to this ticket should be to state, very clearly, in the `README.md` file if:

1. Using `zapzap` still requires the user to first install and create an account in the official WhatsApp app, and all messages are routed through the phone (eg like whatsapp web), or
2. Using `zapzap` still requires the user to first install and create an account in the official WhatsApp app, but afterwords WhatsApp can be uninstalled forever, and the desktop client can replace it (eg like Telegram), or
3. Using `zapzap` is an entirely first-class desktop app. You can create an account in it directly, and you never need to use the official WhatsApp mobile app for any reason (eg like Wire)

Again, please add this information to the `README.md` file -- not to this ticket.

**Comment by rafatosta** [comment]
Did you actually read the Readme?

Thank you for your contribution, but the Readme says it is a PWA for Whatsapp Web with features to improve integration with the desktop.

**Comment by maltfield** [comment]
>  it is a PWA for Whatsapp Web with features to improve integration with the desktop.

I don't even know whtt that means. Can you please add this to the README in plain language?

**Comment by maltfield** [comment]
To clarify, I am not a whatsapp user. I came here looking for a way to use whatsapp on the desktop using an open-source client.

I'm sure a lot of users end-up here asking the same question. Please don't assume that users have experience with whatsapp or terms specific to your app. A README should explain to the average user what the app is in plain language.

I'm still not sure if your app will let me use whatsapp on desktop or not. Please update the readme to make this clear.

**Comment by rafatosta** [comment]
It's all explained, man. Just read the readme!

Site:
https://zapzap-linux.github.io/

Flathub:
https://flathub.org/apps/com.rtosta.zapzap

**Comment by maltfield** [comment]
I read the README. It's still not clear.

Would you be open to a PR to improve it?

**Comment by rafatosta** [comment]
> I read the README, homem.
> 
> It's not clear:
> 
> 1. If `zapzap` will work at all if I never install the official WhatsApp app on my phone
> 2. If `zapzap` will continue to function or not, if I uninstall the WhatsApp app from my phone
> 
> Would you be open to a PR if I type something out for the README to make this clear for the next person who tries to read the README and still walks away with questions?

You should look for this information on the WhatsApp website.

Let's go:
- You need the official Whatsapp installed on your cell phone.
- You cannot uninstall it from your cell phone, but you can use Whatsapp Web or ZapZap if your cell phone was not connected to the internet.
