### ISSUE TITLE
[Flatpak] Dark Mode doesn't change

### ISSUE THREAD

**Issue by RenanSantos7** [zapzap-linux/zapzap#75]
## Description

When I swtich between light and dark mode on Gnome, this change doesn't effect the app, speficly the "WhatsApp Web" part.

### Sytem Details
- **SO**: Fedora Linux 39 (Workstation Edition)
- **GNOME Version**: 45.5 
- **Window system**: Wayland
- **Linux kernel**: Linux 6.8.7-200.fc39.x86_64

### App Details:
- **App Version:**: 5.2 (official compilation)
- **Flatpak version**: 1.15.8

**Comment by rafatosta** [comment]
I identified this little problem a few days ago and put it at #74

I need a little time because I couldn't reproduce it in a development environment. Via Fedora Copr and local execution it works perfectly. This problem only occurs on flatpak 😕

Thanks

**Comment by rafatosta** [comment]
Resolved
