### ISSUE TITLE
Notificações não somem após visualização em outro dispositivo

### ISSUE THREAD

**Issue by RoinujNosde** [zapzap-linux/zapzap#8]
Se abro a conversa pelo celular, a notificação continua na área de notificações do PC.
O mesmo não ocorre com o WhatsApp Web.

Faz um tempo que não mexo com Qt, mas vou dar uma olhada. Ver se acho algum evento pra isso...

**Comment by rafatosta** [comment]
Se tiver algo relacionado a isso é nesta classe [QWebEngineView](https://doc.qt.io/qt-6/qwebengineview.html).

Realmente isso acontece porque apenas faço o envio da notificação via DBus e não há nenhum controle ou gerenciamento. Apenas que ao clicar em uma notificação abre a janela do Zapzap no usuário da mensagem.

**Comment by RoinujNosde** [comment]
https://doc.qt.io/qt-6/qwebenginenotification.html#closed

Esse é o sinal

**Comment by rafatosta** [comment]
> https://doc.qt.io/qt-6/qwebenginenotification.html#closed
> 
> Esse é o sinal 

Esse mesmo. Vou olhar isso agora pela tarde e vejo o que dá pra fazer. Não lembro se guarda alguma referência da notificação que é disparada pelo DBus. 

Vou testar utilizando as próprias notificações do WebView. Da última vez que fiz esse teste, há muito tempo, as notificações estavam bugadas e estranhas.

**Comment by rafatosta** [comment]
Usando as notificações próprias do QWebEngineView aparece a foto do contato como um ícone na barra e não acontece nada ao clicar no ícone.
![image](https://github.com/zapzap-linux/zapzap/assets/18619894/f3fabec8-ac27-4fc6-baff-008257f19452)

As notificações aparecem normalmente, porém não aparece o popup com a mensagem e o contato. E as notificações não somem ao ver pelo celular.
![image](https://github.com/zapzap-linux/zapzap/assets/18619894/abb359d5-a0b6-4058-911b-469b25affd58)

Ou seja, terá que ser implementado. =D

**Comment by RoinujNosde** [comment]
Boa!

Não tá no flathub ainda, né?

**Comment by rafatosta** [comment]
> Boa!
> 
> Não tá no flathub ainda, né?

Ainda não.

Notei que quando tem várias notificações de um mesmo contato só fecha a última. Tô testando para ver se foi algo pontual ou irei precisar criar uma lista de notificações abertas para que nenhuma referência se perca e feche todas.

**Comment by RoinujNosde** [comment]
No WhatsApp Web, quando um contato manda mais de uma mensagem, apenas a última é exibida. Como será que eles fazem isso? Aparentemente não é fechando a notificação, pois vc adicionou o sinal para isso.
Será que eles editam a notificação atual?

**Comment by RoinujNosde** [comment]
Parece que notificações tem uma [tag](https://doc.qt.io/qt-6/qwebenginenotification.html#tag-prop), poderia usar essa como chave em um mapa. (Dict em python?)
tag -> notification

Ao receber uma notificação, verifica se a tag está no dict e cancela a notificação antiga, salva a nova no dict.
O que acha?

**Comment by rafatosta** [comment]
> Parece que notificações tem uma [tag](https://doc.qt.io/qt-6/qwebenginenotification.html#tag-prop), poderia usar essa como chave em um mapa. (Dict em python?) tag -> notification
> 
> Ao receber uma notificação, verifica se a tag está no dict e cancela a notificação antiga, salva a nova no dict. O que acha?

Parece ser a solução!
Atualmente a implementação do dbus que utilizo gera um ID para cada nova notificação e coloca em um dict.

![image](https://github.com/zapzap-linux/zapzap/assets/18619894/1a026adb-59f7-4a83-9554-0b8cfcf1442f)

posso utilizar essa tag para facilitar os fechamentos das notificações antigas.

**Comment by rafatosta** [comment]
@RoinujNosde atualização lançada... agora é só esperar chegar a atualização.
Obrigado pela contribuição!

**Comment by RoinujNosde** [comment]
https://github.com/zapzap-linux/zapzap/blob/f77c95da5a26752dfb0e4629fa7ebe506fcd4f49/zapzap/services/dbus_notify.py#L63

Esse último commit quebrou essa lógica. Alguns métodos ainda esperam que a chave do dict seja o ID.
